### ISSUE TITLE
Integer keys in dicts

### ISSUE THREAD

**Issue by indigoviolet** [rtyler/py-yajl#10]
In this case, I prefer what yajl does [failing to deserialize the data instead of what json does: convert the integer keys to strings]. It might be nicer to either (a) support integer keys or (b) fail on dumps(), instead of loads(). 

yajl.dumps({1:2})
'{1:2}'

yajl.loads(yajl.dumps({1:2}))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: parse error

json.loads(json.dumps({1:2}))
{u'1': 2}

**Comment by rtyler** [comment]
Resolved in SHA: f40427c52c0b2ba657371fdcea98a631fa1363f8
