### ISSUE TITLE
yajl rounds floats to 6 digits

### ISSUE THREAD

**Issue by indigoviolet** [rtyler/py-yajl#21]
<pre>
In [12]: yajl.dumps([1.0/3])
Out[12]: '[0.333333]'

In [13]: json.dumps([1.0/3])
Out[13]: '[0.33333333333333331]'
</pre>

I didn't notice anything in the JSON rfc that set the precision.

**Comment by indigoviolet** [comment]
This is obviously coming from yajl's yajl_gen_double() function where it's doing an sprintf("%g"), which sets it to 6 digits by default. Is there a way around it?

**Comment by indigoviolet** [comment]
Also see related issue that I opened on the yajl github: http://github.com/lloyd/yajl/issues#issue/15

**Comment by rtyler** [comment]
Resolved with SHA: 44e8588f23b058b7ee930120c5a6a453aef10c42
