### ISSUE TITLE
Don't silently skip over tuples

### ISSUE THREAD

**Issue by indigoviolet** [rtyler/py-yajl#8]
Either convert them to lists of size 2, or throw an error.

In [4]: yajl.dumps([(2, 3)])
Out[4]: '[]'

**Comment by rtyler** [comment]
Good catch, the `json` module in Python 2.6 converts to lists, so I think I'll add that

```
>>> json.dumps([(2,3,)])
'[[2, 3]]'
```

**Comment by rtyler** [comment]
Resolved in SHA: e5bfbe1ac69b6cac829d32acc813caff8cbb1a52

**Comment by indigoviolet** [comment]
Fantastic!

This is an incredibly useful library, and I'm always impressed by how quickly you respond to reports. Thank you.
