### ISSUE TITLE
Raise an exception when objects inside a data structure cannot be processed

### ISSUE THREAD

**Issue by indigoviolet** [rtyler/py-yajl#9]
Oh, sorry to report this separately, but sets have the same issue as #8. In general, it seems like it would be nice to raise an exception when an object inside a list (for example) cannot be processed.

In [2]: yajl.dumps(set([3,4]))

ValueError Traceback (most recent call last)
in ()

ValueError: Failed to process

In [3]: yajl.dumps([set([3,4])])
Out[3]: '[]'

(json cannot do this earlier, but raises an exception).

**Comment by rtyler** [comment]
Another good catch, `json.dumps` throws a `TypeError`, so we should probably not be throwing the `ValueError` there

**Comment by rtyler** [comment]
This also highlights a bug that already existed, if a list contains an unserializable object `yajl.dumps`  would simply return a `'[]'` instead of raising the TypeError

**Comment by rtyler** [comment]
Resolved with SHA: 9d8d1a4dc46df1f9161bcaba9d3da163d9811271

**Comment by indigoviolet** [comment]
And thanks again!
